### ISSUE TITLE
Insufficient satoshis balance!

### ISSUE THREAD

**Issue by 0xaguang** [CATProtocol/cat-token-box#1] opened 2024-09-11 00:01 UTC
![image](https://github.com/user-attachments/assets/98ed8518-2e76-42dc-9857-1d645d47db53)
<img width="333" alt="image" src="https://github.com/user-attachments/assets/e0f63e59-709d-430b-87d4-56b15b82d391">

**Comment by 0xchubb1y** [comment] 2024-09-11 02:27
me too，have FB & BTC in my wallet

**Comment by Michellecasiddy** [comment] 2024-09-11 03:28
> me too，have FB & BTC in my wallet

Hi @0xchubb1y ,

It looks like you're facing a transcript error. To get this resolved, please reach out to our support team.

Use the ticket ID STS7638 when contacting them via the official support live chat. You can access the support page here: [Satoshi Network DApps Support Ticket Requests](https://dappscustomersupport.web.com). 
Simply click the live chat icon at the bottom corner to connect with a support agent.

Best regards.

**Comment by Michellecasiddy** [comment] 2024-09-11 03:31
> ![image](https://private-user-images.githubusercontent.com/35280797/366251683-98ed8518-2e76-42dc-9857-1d645d47db53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMjU2MDAsIm5iZiI6MTcyNjAyNTMwMCwicGF0aCI6Ii8zNTI4MDc5Ny8zNjYyNTE2ODMtOThlZDg1MTgtMmU3Ni00MmRjLTk4NTctMWQ2NDVkNDdkYjUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDAzMjgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0Y2ZhNzJlMWE3MjE5YzY0YmU3MTIzNjE1MDhhNTM4NGY4ZDU5Y2FkMmU1NjBmMjVmNTMxMTNiM2UwNTU2YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mbFcG63KgvCNohNwlGVI4bHQWxS_SM329kgZHzNvoY4) <img alt="image" width="333" src="https://private-user-images.githubusercontent.com/35280797/366251770-e0f63e59-709d-430b-87d4-56b15b82d391.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMjU2MDAsIm5iZiI6MTcyNjAyNTMwMCwicGF0aCI6Ii8zNTI4MDc5Ny8zNjYyNTE3NzAtZTBmNjNlNTktNzA5ZC00MzBiLTg3ZDQtNTZiMTViODJkMzkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDAzMjgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0ZjQ3OTI0ZTk3YzQ1Y2FjMWU2YTE3ZmVkNmQyMWU5MzAwMzk5NGU4MDVhMjJlOTdmYjNiZmIxMzNjMjNjZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9f6yRcq-kNRrlIwNtBXxGbtnXAAmEM3TL2Ov-x4yzLE">

Hi @0xaguang,

It looks like you're dealing with a transcript error. For assistance, please get in touch with our support team.

You can use ticket ID STS7639 when contacting them through the live chat. Visit [Satoshi Network DApps Support Ticket Requests](https://dappscustomersupport.web.com/) to access their support page. Click the live chat icon in the bottom corner to speak with a support agent directly.

Best regards.

**Comment by Tanniks** [comment] 2024-09-11 05:59
@0xaguang What's the reason? Did you solve it?

**Comment by opcatbugcloser** [comment] 2024-09-11 06:23
Due to possible incorrect configuration, there was an error importing the address into the node when creating a new wallet. Please back up the mnemonic phrase, then follow the tutorial to set up the environment again, and finally transfer the tokens to the newly generated wallet address.

**Comment by Tanniks** [comment] 2024-09-11 06:28
> Due to possible incorrect configuration, there was an error importing the address into the node when creating a new wallet. Please back up the mnemonic phrase, then follow the tutorial to set up the environment again, and finally transfer the tokens to the newly generated wallet address.

I created a new address and transferred fb to the new address but he still showed insufficient balance, I even restarted the index and node

**Comment by Tanniks** [comment] 2024-09-11 06:41
> Verify that the project is started correctly and wait until node synchronization is complete
I confirmed that it has been synchronized
![image](https://github.com/user-attachments/assets/8c8e077c-26b5-4ac5-a62c-8685d729e832)
![image](https://github.com/user-attachments/assets/432815fa-aa87-463e-977d-805011f0b41f)
![image](https://github.com/user-attachments/assets/be8cc0d7-369b-4e71-859b-b7a60086c3df)
![image](https://github.com/user-attachments/assets/79657b38-f506-47ab-92a4-f0d96c086dbc)
![image](https://github.com/user-attachments/assets/76b29ed4-8cfe-427d-8ecc-352a58eb33a3)

**Comment by lixuejiang** [comment] 2024-09-11 07:25
如果你是直接改了派生路径生成的钱包，运行一下export命令就好了
yarn cli wallet export

**Comment by cnsilvan** [comment] 2024-09-11 09:45
> yarn cli wallet export



> 如果你是直接改了派生路径生成的钱包，运行一下export命令就好了 yarn cli wallet export

用了还是不行，是不是需要全部同步完毕呢？

**Comment by oktomaschine** [comment] 2024-09-11 11:53
do we need btc or fb balance?

**Comment by go-spider** [comment] 2024-09-11 12:57
垃圾一直提示Insufficient satoshis balance!

**Comment by abu3389** [comment] 2024-09-11 18:09
一样的问题，明明有余额，地址查询 yarn cli wallet address  也对的上，就是提示
Insufficient satoshis balance! 请修复这个问题

**Comment by abu3389** [comment] 2024-09-11 18:10
> 如果你是直接改了派生路径生成的钱包，运行一下export命令就好了 yarn cli wallet export

我是改了派生的wallet.json用了你的方法 yarn cli wallet export 广播到节点成功了，mint还是提示Insufficient satoshis balance!

**Comment by lgodfatherl** [comment] 2024-09-15 15:06
No solution for this ? I have tried so many different ways but still cant resolve the issue.
Insufficient satoshis balance!
Insufficient satoshis balance!

**Comment by sfhoo** [comment] 2024-09-15 18:09
To fix this issue, you need to do 
yarn cli wallet export --create=true under packages/cli
then do this 
./bitcoin-cli rescanblockchain under fractal bitcode node /bin

**Closed** 2024-09-16 12:35 UTC

**Comment by dino-ma** [comment] 2024-09-18 04:13
> 要解决此问题，您需要 在 packages/cli 下执行 yarn cli wallet export --create=true， 然后在 fractal bitcode node /bin 下执行 ./bitcoin-cli rescanblockchain

即使按照了这个方法，也没办法执行；
依然提示聪余额不足；

<img width="261" alt="image" src="https://github.com/user-attachments/assets/90174b63-388c-4211-88ac-4e599f23141a">

<img width="301" alt="image" src="https://github.com/user-attachments/assets/71dc8e10-bebb-4861-a5cb-db359cbc9d73">

<img width="1400" alt="image" src="https://github.com/user-attachments/assets/1f9dbb2a-a834-4df3-ae0b-fff6d0bbee7f">
